name: learn-github-actions
on: [push]
jobs:
  ci-server-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout the code
      - run: echo hello world
        name: print the message
      - run: ls -ltr
        name: list all files
